### ISSUE TITLE
Clean Install - jQuery Error

### ISSUE THREAD

**Issue by vfontjr** [copyblogger/genesis-sample#100]
This error occurs on a clean install of genesis sample:

ReferenceError: wp is not defined
genesis-sample.js:45:7

The corrected code is:
if (typeof wp != "undefined" && typeof wp.customize != "undefined") {

**Comment by nickcernis** [comment]
Thank you for this, Victor.

I don't see the same error with a fresh install (logged out or logged-in, I tested Firefox and Chrome), but your check in https://github.com/copyblogger/genesis-sample/pull/101 is a good precaution in case the `wp` object isn't available.

**Comment by bgardner** [comment]
Closing per https://github.com/copyblogger/genesis-sample/commit/ac8685262e966e91174ce93d1f283e0ef91bb44d
