### ISSUE TITLE
WooCommerce' CSS loading on all the pages

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#111]
lib/woocommerce/genesis-sample-woocommerce.css is loading site-wide.

Ex.:

`<link rel='stylesheet' id='genesis-sample-woocommerce-styles-css'  href='https://genesis-sample.test/wp-content/themes/genesis-sample/lib/woocommerce/genesis-sample-woocommerce.css?ver=2.6.0' type='text/css' media='screen' />`

I think it should be loading only on WooCommerce related pages.

**Comment by damiencarbery** [comment]
If a site owner uses WooCommerce shortcodes outside of a WooCommerce page then these styles might be needed. The [is_woocommerce()](https://github.com/woocommerce/woocommerce/blob/3.4.1/includes/wc-conditional-functions.php#L20) function would not be enough to determine whether the styles are needed.

**Comment by robincornett** [comment]
It looks like that stylesheet is loaded using the `woocommerce_enqueue_styles` filter, rather than being enqueued independently, so I think any decision about whether it should load or not is actually being handled by Woo, not the sample theme.

**Comment by dreamwhisper** [comment]
While I like to optimize as much as possible, due to WooCommerce shortcodes and widgets, these styles are necessary on any page at this point.
