### ISSUE TITLE
Cross Site Scripting vulnerabilities

### ISSUE THREAD

**Issue by broros** [copyblogger/genesis-sample#114]
are you checking for vulnerabilities?

![malawre-sucuri](https://user-images.githubusercontent.com/598228/42431011-a78ce6a8-82f7-11e8-93e0-beb48ecf6214.png)

**Comment by nickcernis** [comment]
@broros The malware in these screenshots does not appear to relate to any files that Genesis or Genesis Sample serves. Genesis itself is peer-reviewed and security audited. We're not aware of any security issues and we haven't seen reports of malware being introduced via Genesis.

If you believe this malware report is accurate and wish to clean the site, I recommend these resources:

- https://codex.wordpress.org/FAQ_My_site_was_hacked
- https://sucuri.net/guides/how-to-clean-hacked-wordpress
- https://askwpgirl.com/10-steps-remove-malware-wordpress-site/

If anyone has security-related reports with steps to reproduce a vulnerability, we encourage them to disclose this responsibly by emailing `support@studiopress.com`.

This repo is for issues relating to the Genesis Sample child theme only. For Genesis issues and questions you're welcome to [get help here](https://my.studiopress.com/help/). I hope that helps!
