### ISSUE TITLE
genesis-sample theme doesn't pass phpcs

### ISSUE THREAD

**Issue by lamw** [copyblogger/genesis-sample#115]
I just cloned the sample repo and ran through the tutorial for validating phpcs and it looks like its not currently passing, not sure what the fix needs to be but someone may want to have a look

````
FILE: /Users/wlam/git/genesis-sample/functions.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 120 | ERROR | Variables defined by a theme/plugin should start with the
     |       | theme/plugin prefix. Found: "$content_width".
     |       | (WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound)
----------------------------------------------------------------------

Time: 1.64 secs; Memory: 32.75Mb

Script phpcs handling the phpcs event returned with error code 1
```

**Comment by rrennick** [comment]
$content_width is required in theme functions file. See https://codex.wordpress.org/Content_Width#Adding_Theme_Support

The tests probably need to have an exclusion added.

**Comment by nickcernis** [comment]
Thank you for the report and suggestion.

This is fixed in https://github.com/copyblogger/genesis-sample/commit/5a51a24c45d16a82b44d5f71c86be7b350d7cc7a (now in the develop branch).
