### ISSUE TITLE
Width and height of featured images in the Featured Posts widgets

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#116]
Per https://github.com/copyblogger/genesis-sample/blob/5a51a24c45d16a82b44d5f71c86be7b350d7cc7a/style.css#L858-L861 featured images output by the Genesis Featured Posts widget (haven't checked the Featured Pages widget) always appear 75 x 75.

Is there a reason why these are hardcoded? Shouldn't the image size selected in the widget be used and shown on the frontend?

**Comment by bgardner** [comment]
This has already been reported and fixed (https://github.com/copyblogger/genesis-sample/issues/112)

**Comment by bgardner** [comment]
Also noting that the idea with the CSS is to provider a crisp image, as the image output is at 150x150, but scaled down to 75px for 2x.
