### ISSUE TITLE
z-index on .genesis-nav-menu .sub-menu 

### ISSUE THREAD

**Issue by neilgee** [copyblogger/genesis-sample#17]
Any chance of setting a z-index higher on submenus

**Comment by GaryJones** [comment]
For what reason?

**Comment by neilgee** [comment]
Well, i find a lot of slider or hero style elements typically use a higher z-index such as 9999 and they sit quite often just below a menu and then obscure a submenu when hovered.

**Comment by GaryJones** [comment]
Then the problem lies with the slider and hero style elements. Encourage their authors to use sensible numbers.
