### ISSUE TITLE
Remove Duplicate CSS

### ISSUE THREAD

**Issue by laurenmancke** [copyblogger/genesis-sample#24]
This CSS on line 1514:
```
	.sidebar-primary,
	.title-area {
		width: 300px;
	}
```
is duplicated just below it starting on line 1519:
```
	.footer-widgets-1,
	.footer-widgets-2,
	.footer-widgets-3,
	.sidebar-primary,
	.title-area {
		width: 300px;
	}
```

**Comment by laurenmancke** [comment]
@nathanrice I can do this if you give me access to commit

**Comment by nathanrice** [comment]
Done. Does it need to be fixed in Genesis too?

**Comment by laurenmancke** [comment]
@nathanrice no it was just added when you added back in the footer widgets to genesis sample
