### ISSUE TITLE
Table of contents: Skip Links

### ISSUE THREAD

**Issue by laurenmancke** [copyblogger/genesis-sample#25]
Skip Links are in the wrong spot in the table of contents

**Comment by GaryJones** [comment]
Now they are in there twice.

**Comment by bgardner** [comment]
Nope -- https://github.com/copyblogger/genesis-sample/commit/f64323098aeafaf91af7f084681fd5f7587fb382 (just forgot to reference the issue with this commit)

**Comment by laurenmancke** [comment]
@nathanrice this does need to be fixed in Genesis as well
