### ISSUE TITLE
Version number missing from Theme View

### ISSUE THREAD

**Issue by jdelia** [copyblogger/genesis-sample#27]
The version number is missing from this view:

<img width="1514" alt="screen shot 2016-02-23 at 9 09 29 pm" src="https://cloud.githubusercontent.com/assets/3217274/13273507/dc4275a6-da71-11e5-8eb6-a1c9f02d8d45.png">

It appears the style.css does not have Version: x.x.x in the header. It has the template version, but not version which results in the version number not being displayed when view the theme details page.

**Comment by GaryJones** [comment]
Aside: `Template Version` does absolutely nothing, and should be removed in case WP does implement a header for that later on but with different conditions to expected.
