### ISSUE TITLE
Cleaning up lib/output.php

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#44]
lib/output.php has an unused function, genesis_sample_change_brightness().

It is referenced in line 111 wherein it is sent as an argument but there's no placeholder using it.

Also `%1$s` and `%2$s` could be changed to `%s` as they are not being used more than once.

In summary, I think that file can be cleaned up like this: http://pastebin.com/raw/khcGg4Ww

Discussion: https://genesiswp.slack.com/archives/general/p1463835619000921 or http://d.pr/i/gVAO

**Comment by laurenmancke** [comment]
line 73 should also use `%s`
