### ISSUE TITLE
Replacing get_stylesheet_directory_uri() with CHILD_URL

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#45]
I was advised by Tonya the following:

> Genesis defines the constant CHILD_URL in the init.php.  You can use it instead of calling get_stylesheet_directory_uri() to be more performant.  Why? It takes time for PHP to call the function multiple times.  The value is already stored for us in the Genesis constant, CHILD_URL.

As such

`wp_enqueue_script( 'genesis-sample-responsive-menu', get_stylesheet_directory_uri() . '/js/responsive-menu.js', array( 'jquery' ), '1.0.0', true );`

in functions.php can be changed to

`wp_enqueue_script( 'genesis-sample-responsive-menu', CHILD_URL . '/js/responsive-menu.js', array( 'jquery' ), '1.0.0', true );`

**Comment by srikat** [comment]
On a similar note, `get_stylesheet_directory()` could be replaced with `CHILD_DIR` and `get_template_directory()` with `PARENT_DIR`.

**Comment by GaryJones** [comment]
`CHILD_*` and `PARENT_*` are only in Genesis for back-compat I think. Yes, you might save a function call, but that is a micro-optimization at the expense of using the core function(s) and consistency with every non-Genesis tutorial out there for enqueueing scripts.

**Comment by laurenmancke** [comment]
I agree with @GaryJones on this one

**Comment by paaljoachim** [comment]
I happen to do a search on CHILD_URL vs get_stylesheet_directory_uri Genesis when I came across this thread. I would say go with the default WordPress way as much as possible for all code.
