### ISSUE TITLE
Conflict with TOC+

### ISSUE THREAD

**Issue by waybis** [copyblogger/genesis-sample#51]
Hi, I just replaced an old Genesis sample child theme with this new one, which on the whole went well, the only problem I experienced was a conflict with the TOC+ plugin, if there is a [toc] shortcode on a page it would throw up a fatal error:

Fatal error: Cannot redeclare genesis_sample_color_contrast() (previously declared in /homepages/12/d230748768/htdocs/s1-com-v2-wp/wp-content/themes/s2/lib/output.php:30) in /homepages/12/d230748768/htdocs/s1-com-v2-wp/wp-content/themes/s2/lib/output.php on line 30

It's not a big deal since the TOC+ works fine when auto-adding table of contents, it's only when you add the [toc] shortcode manually to reposition or add a TOC to an excluded page.

I've only modifed the style.css and functions.php and have not touched the output.php file.

Any thoughts on wat is happening?  I only modifed the style.css and functions.php and have not touched the output.php file.

**Comment by GaryJones** [comment]
Either lib/output.php is being required twice (resulting in `genesis_sample_css()` being hooked in twice) or something is calling `genesis_sample_css()` manually a second time. I'm not sure how the TOC+ plugin works (and haven't got time to debug), but it sounds like it's doing something a little odd.

FWIW, this is one reason why nested functions are a bad idea.

**Comment by waybis** [comment]
Thanks Gary, I've had another look and perhaps it's becasue I've changed the link color to #0066cc in style.css but I noticed customize.php has a default link color of #c3251d, so I'm wondering if that is causing the upset with genesis_sample_css() 

Perhaps I should modify genesis_sample_customizer_get_default_link_color() in customise.php and see what happens.

**Comment by waybis** [comment]
Looks like something I've changed in the sample theme, just tried the sample theme without changes and it works fine.

**Comment by waybis** [comment]
Oops perhaps not, loaded the old sample theme 2.0.1 by mistake, tried with new sample theme 2.2.4 without modifications and same fatal error when using [toc] shortcode...I'll reach out to the TOC+ plugin and see whether they can gleam anything on the issue.

**Comment by rrennick** [comment]
The plugin runs do_action( 'wp_enqueue_scripts' ) inside the shortcode rendering. WordPress has already run the hook. While it is fine to repeat filter calls, hooks should not be run multiple times.

**Comment by waybis** [comment]
Thanks for taking a look Ron, best avoid the [toc] shortcode then for now.

**Comment by waybis** [comment]
Hi,
Thanks for getting back to me.

Ron has answered on github here:
https://github.com/copyblogger/genesis-sample/issues/51#issuecomment-225625375

So unless there is anything in addition, the issue is closed from my point
of view.


Thanks.

Wayne

**Comment by GaryJones** [comment]
@waybis You may want to check which email you just replied to :-)

**Comment by waybis** [comment]
Oops, thanks Gary.
