### ISSUE TITLE
Template Version

### ISSUE THREAD

**Issue by neilgee** [copyblogger/genesis-sample#53]
Shouldn't Template Version be 2.3.0

**Comment by GaryJones** [comment]
Template Version should be dropped completely - it's not used in WP Core, and if it did, then it may be used in a way which isn't expected (i.e. coubt as a maximum version or some other weird logic).

Let's not try to pre-empt WP core, or add things that aren't used by anything anyway.

**Comment by bgardner** [comment]
I'm going to close this after recent discussion with @nathanrice.

**Comment by GaryJones** [comment]
But with what outcome? Drop Template Version? Update it to something else? It's not consistently used in [Genesis] child themes and doesn't actually do anything right now.

**Comment by bgardner** [comment]
I'll let @nathanrice explain this.....

**Comment by nathanrice** [comment]
It would be so incredibly useful if it actually worked. Even if WP would allow you to filter the default values it pulls from the style.css header in `wp_get_theme()`.

But as it stands, to even make this work with our own code, it would require a semi-expensive and unnecessary extra parse of the style.css header.

It would actually be better to use a PHP solution than a tag in the style.css file.

So yes, this can be removed from the style.css file.
