### ISSUE TITLE
Use .no-js instead of .js?

### ISSUE THREAD

**Issue by leighanthony** [copyblogger/genesis-sample#55]
Currently the sample theme adds a .js class to the body when JavaScript is enabled. The mobile menu styles are then applied to nav items. There is a slight delay in adding the .js class which causes visitors to briefly see the non-js version of the nav menu items.

A better solution would be to have a .no-js body class and remove it if JavaScript is enabled. Only 1% of browser requests have JS disabled on average so it makes sense to support the majority of users.

This would also result in less css styles needed to achieve the same result.

**Comment by leighanthony** [comment]
Tried this, didn't work. Still a slight delay in removing the .no-js class (should have known that).

**Comment by GaryJones** [comment]
Relevant: https://github.com/garyjones/genesis-js-no-js
