### ISSUE TITLE
Update .screen-reader-text styling?

### ISSUE THREAD

**Issue by nathanrice** [copyblogger/genesis-sample#63]
Crossposting this from the Genesis repo:
https://github.com/copyblogger/genesis/issues/1493

What we do in Genesis needs to be done here too.

**Comment by dreamwhisper** [comment]
@nathanrice this is all that we added correct? https://github.com/copyblogger/genesis-sample/blob/develop/style.css#L545

We started including that in theme updates.

**Comment by nathanrice** [comment]
Yep, that's it!
