### ISSUE TITLE
Use custom-logo instead of custom-header

### ISSUE THREAD

**Issue by seothemes** [copyblogger/genesis-sample#65]
Themes should really be using the custom logo theme feature instead of custom header for uploading site logos. This outputs better markup and is more flexible, it also free's up the custom header which can then be used for something else. Child themes can use custom logos easily without having to change anything in Genesis.

**Comment by bgardner** [comment]
Closing per https://github.com/copyblogger/genesis-sample/commit/d6fe79d9e23390b3bf6464213da625d9b4701d41.

**Comment by dreamwhisper** [comment]
Tasks:
- Remove `'header-text' => array( '.site-title', '.site-description' ),` - this adds a checkbox to display the header text/description. But, we don't want that to display if a logo is uploaded. (We hide it with CSS regardless)
- Remove Genesis Dynamic text controls from the customizer and theme settings
- Review logo size (area)

**Comment by dreamwhisper** [comment]
Closed with https://github.com/copyblogger/genesis-sample/pull/93
