### ISSUE TITLE
 Genesis Customizer Widget Controls Not Expanding in WP 4.8

### ISSUE THREAD

**Issue by MattRhodes** [copyblogger/genesis-sample#68]
Our website is running Genesis Framework 2.52 & Genesis Sample 2.30. We upgraded to WordPress 4.80 & now the Customize Widgets page has stopped working. Won't expand the Primary, Secondary Sidebars or the Footers. Used a backup to show that it works in 4.75, but dies after the 4.80 upgrade. Can't get to Customize Header either. I also tried switching the theme to WordPress 2016 & then upgrading to 4.80. Customize Widgets page works for 2016 theme, but then switching back to Genesis Sample 2.30 breaks it. Any ideas to restore the functionality?

**Comment by nathanrice** [comment]
Is it just the sample theme, or is it all Genesis child themes?

**Comment by MattRhodes** [comment]
Another website I work on is using Modern Studio Pro theme & that survived the 4.80 upgrade. Differing plugins on the 2 sites, though. Hmm, I could put the Genesis Sample theme on the working website & see if it breaks there too (after a backup, of course).

**Comment by MattRhodes** [comment]
Tried Genesis Sample on the website that survived the WordPress 4.80 upgrade & the customize widgets page worked like normal. Created a test WordPress 4.80 installation in a subdomain & then added Genesis Framework & Sample to it.  That works too. Must be a widget creating plugin that is causing the problem. Will start adding plugins from the broken site to the test site to see if I can find a plugin that isn't playing nice with 4.80.

**Comment by MattRhodes** [comment]
It's more complicated than I thought. I tried Modern Studio Pro on the broken website & it's busted with that theme as well. I tried nuking plugins till nothing was installed, but Customize under Appearance still comes up empty, no options listed. Widgets under Appearance comes up, but the sidebars, footers & header right won't expand & the widgets don't move when you try to drag them. I then tried switching to the 2017, upgrading to 4.80 & those menus work, but not when I switch to Genesis 2.5.2 & Sample 3.0. I tried nuking pages thinking maybe that caused problems. Moved them to trash & then upgrading (still no plugins). Got down to 1 page & the upgrade kills, but not with 0 pages. Problem is it didn't seem to matter which page was left. I restored an older backup where the widgets page was frozen & now it wasn't frozen, but the Appearance Customize still comes up empty. I was thinking about trying to single step thru the onclick routine for the down arrows on the sidebars or footers. My feeling at this point is that it a bug in the Framework rather than the child theme, but I can't quite find the trigger for it. Maybe something will makes sense to you, since you more likely know more about how Customize & Widgets look under the hood.

**Comment by GaryJones** [comment]
Any errors in the browser console when you load the page, and when you try to expand a widget area in the Customizer sidebar?

(Also, please re-title this Issue, to better describe the actual problem, rather than just "Trouble" i.e. Genesis Customizer Widget Controls Not Expanding in WP 4.8)

**Comment by MattRhodes** [comment]
There are a bunch of errors. First time I looked I saw errors about unterminated strings & a reference error about tinymce being undefined. Searching online I found a post on StackOverflow recommending define('CONCATENATE_SCRIPTS', false); in the wp-config.php. That helped. Appearance Customize is no longer empty & Appearance Widgets is responsive in both Chrome & Firefox. Wasn't for Firefox before. Will roll back to WP 4.75, because the site is still incredibly sluggish. Doesn't get better with all plugins deactivated.

**Comment by GaryJones** [comment]
With concatenation set to false, can you please share a screenshot of the first sets of errors in the console?

**Comment by MattRhodes** [comment]
Here's 3 screenshots. 1st with default concatenation, 2nd concat false w/js errors & 3rd concat false w/css warnings. The js error about NS_ERROR_FAILURE makes me wonder if maybe somehow 2 modules are trying to define a namespace with the same name.

![widgetsdefaultconcatenation](https://user-images.githubusercontent.com/29466559/27333316-7daa9f3e-5593-11e7-8dab-67cd31f207fb.PNG)

![widgetsconcatenationfalse](https://user-images.githubusercontent.com/29466559/27333345-907593e4-5593-11e7-8571-da01fe954aa2.PNG)

![widgetsconcatenationfalsecsswarnings](https://user-images.githubusercontent.com/29466559/27333352-95a988c0-5593-11e7-8c15-bfb297fb6728.PNG)

**Comment by GaryJones** [comment]
The `NS_ERROR_FAILURE` looks like it can be clicked to show more detail.

Of the rest, none of the filenames look related to Genesis or Sample, so there's little that can be fixed via this repo.

A re-install of WP might be needed.

**Comment by MattRhodes** [comment]
Didn't notice that. I was trying to look at admin.php line, but having a hard time figuring out where on the line the error was.

![widgetsconcatenationfalsensdetails](https://user-images.githubusercontent.com/29466559/27333902-7aaef576-5595-11e7-99ad-c61097d87f8e.PNG)

**Comment by MattRhodes** [comment]
Not sure I know why but the sluggish performance has gone away. Perhaps our webhost (Arvixe) was having server issues, although I don't see anything in the status log that pertains to us. Not sure why the define('CONCATENATE_SCRIPTS', false); in the wp-config.php should matter after the upgrades, but that solved the problems with the theme's Appearance Customize & Appearance Widgets pages. Bottom line is the website seems back up & running. Thank you both for all the help.
