### ISSUE TITLE
Beta: button text uses custom color instead of white/black when visiting the page it links to

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-sample#74]
1. Create a menu link with class 'menu-highlight' that points to a subpage.
2. Give the Link Color a dark color:
    
    <img width="284" alt="customize__sample_page" src="https://user-images.githubusercontent.com/647669/36160384-515eeb88-10e1-11e8-85eb-032afff5c4f1.png">

3. Click the button to visit its subpage.

The button text has the active page custom color instead of white / black, making it hard to read:

<img width="367" alt="sample_page" src="https://user-images.githubusercontent.com/647669/36160149-c6284208-10e0-11e8-9298-45c7a9705112.png">

**Comment by bgardner** [comment]
@nickcernis Care to see if this is any better?

**Comment by nickcernis** [comment]
@bgardner Perfect!

I confirmed the button now takes active colors when in current page state and works with a variety of custom color choices.

![screen shot on 2018-02-13 at 19_56_55](https://user-images.githubusercontent.com/647669/36168048-22974716-10f8-11e8-858e-af56049b9e77.png)
