### ISSUE TITLE
Beta: "No sidebars" - class "genesis-content" no change width

### ISSUE THREAD

**Issue by KitsuneSolar** [copyblogger/genesis-sample#75]
After "Select Default Layout" -> "No sidebars", class "genesis-content" no change width.

Fix: add `width: auto;`

```
.full-width-content .content,
.landing-page .content {
  float: none;
  margin-left: auto;
  margin-right: auto;
  width: auto;
}
```

**Comment by bgardner** [comment]
Closing this, as the intent is to maintain the 65% width from:

```
.content {
	float: left;
	width: 65%;
}
```

And not make the content width 1080px, which makes text very unreadable. While .full-width-content is the actual markup, the idea here is for it to be more of a no-sidebar concept.
