### ISSUE TITLE
Consider dropping position: fixed for .site-header at mobile widths

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-sample#80]
At mobile widths when logged in, there's a gap above the header when you scroll down:

![slack-imgs](https://user-images.githubusercontent.com/647669/36741708-14b80d94-1be6-11e8-93f2-925a9fcb0070.png)

---

Lower menu items are also inaccessible at small widths if there are many of them (because the menu's fixed):

![screen shot on 2018-02-27 at 17 47 54](https://user-images.githubusercontent.com/647669/36741827-626445b2-1be6-11e8-944c-bf3ac5219961.png)

I recommend removing `position: fixed` for `.site-header` at small widths and only applying it at larger widths to solve both issues.

**Comment by dreamwhisper** [comment]
💯

**Comment by bgardner** [comment]
@nickcernis Can you test now?

**Comment by nickcernis** [comment]
@bgardner 👍 Looks great at all widths and the menu is now accessible.
