### ISSUE TITLE
Gutenberg: Add Theme Colors

### ISSUE THREAD

**Issue by bgardner** [copyblogger/genesis-sample#81]
As it states, adding theme colors.

**Comment by bgardner** [comment]
@nickcernis Can you test this when you have some time?

**Comment by bgardner** [comment]
Expected behavior:

![screencapture-localhost-8888-wp-admin-post-php-1520100592602](https://user-images.githubusercontent.com/486261/36937627-d41dd1c6-1edb-11e8-80c1-03cb636e6234.png)

**Comment by nickcernis** [comment]
Looks good! Confirmed:

- Default colors appear in background and text color options.
- Colors update when theme colors are edited in the Customizer.
- Regular color picker is still available.

![colours](https://user-images.githubusercontent.com/647669/36985105-ad3fb6c0-2096-11e8-8f4f-fd1a42db8727.png)

![customizer](https://user-images.githubusercontent.com/647669/36985137-c2837332-2096-11e8-9b81-f939ebee5199.png)

![custom](https://user-images.githubusercontent.com/647669/36985131-be62ddb0-2096-11e8-9ec5-8910e4682959.png)

**Comment by bgardner** [comment]
@nickcernis When you have a moment, can you please retest this now that it has been added back in?

**Comment by nickcernis** [comment]
Looks good!

![colours](https://user-images.githubusercontent.com/647669/37869599-70b9dec8-2fba-11e8-8ede-a05eb6d08c65.png)
