### ISSUE TITLE
Beta: Remove primary nav's wrap?

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#82]
Since the primary navigation is being relocated to inside the site header, it does not need wrap anymore.

May I suggest the following to be added in `functions.php`?

```
// Removes primary navigation menu's wrap.
add_theme_support( 'genesis-structural-wraps', array(
	'header',
	'menu-secondary',
	'footer-widgets',
	'footer' )
);
```

**Comment by bgardner** [comment]
I wonder if this is truly necessary? Tying to keep functions file to a minimum, and having the wrap in the markup IMO isn't that big of a deal. Plus, it's there for styling purposes in the event someone wants to target it.

**Comment by srikat** [comment]
Agree. It's not a big deal.

Boils down to most lean/essential/bare minimum markup in the frontend vs a bit of extra code in functions.php.

**Comment by dreamwhisper** [comment]
I would say leave the wrap as is.
