### ISSUE TITLE
Beta: Vertical alignment of hamburger menu icon and the "Menu" text

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#83]
With the current font-size of 1.5em for `.menu-toggle::before`, the menu icon and the text do not appear at the same level:

![screenshot](https://d.pr/i/PN5dtU+)

Changing the font-size to 1.4em fixes it (or seems to):

![screenshot](https://d.pr/i/G17BCw+)

Also, for the sake of consistency shouldn't we use px and rem for the units instead of em? (this applies to https://d.pr/i/WfeUxz as well)

**Comment by srikat** [comment]
Doesn't seem to, in my test site at least..

![screenshot](https://d.pr/i/m9JNK0+)

**Comment by bgardner** [comment]
Strange, I see the opposite:

![screen-shot-2018-03-04-at-6 28 25-am](https://user-images.githubusercontent.com/486261/36945535-5e758f28-1f75-11e8-8e1e-79d66edbe4d0.jpg)

Should we just change it from 1.5em to 20px, to stay consistent either way?

**Comment by bgardner** [comment]
Actually, we can leave as is and change line-height on the .menu-toggle to 18px?

**Comment by srikat** [comment]
That makes the vertical alignment even more off. But then it is because the :before psuedo element is appearing at different font size for the two of us.

Let's wait for someone else to test this..

**Comment by nickcernis** [comment]
The Dashicons CSS appears to be loaded at a higher priority than Genesis Sample styles when logged in.

So I see the same as Brian when logged out:

![logged-out](https://user-images.githubusercontent.com/647669/36986815-14239164-209b-11e8-9305-1c712ad37330.png)

![dashicons-logged-out](https://user-images.githubusercontent.com/647669/36987015-a843bdce-209b-11e8-8f5e-69270e9f04f7.png)

And the same as Sridhar when logged in:

![menu-toggle](https://user-images.githubusercontent.com/647669/36986500-3eb205ba-209a-11e8-9ddb-2ea0bc0a71d2.png)

![dashicons-logged-in](https://user-images.githubusercontent.com/647669/36987039-b25d8b3c-209b-11e8-949a-07508d4d95b1.png)

If we change the font size, we may want to add an extra selector so specificity trumps Dashicons when logged in. (e.g. `.site-header .menu-toggle::before`).

1.4em looks better in Chrome and Firefox for me and this works when logged out or in:

```CSS
.site-header .menu-toggle::before {
	font-size: 1.4em;
	margin-right: 5px;
	text-rendering: auto;
}
```

Or `font-size: 22.5px;` if we want to use px values.

**Comment by dreamwhisper** [comment]
Playing with this, and this is the best consistent alignment I am getting across browsers on both Win and Mac:

```.site-header .menu-toggle::before {
	margin-right: 5px;
	text-rendering: auto;
	vertical-align: text-top;
}```

Windows only likes the dashicon at 20px or 25px, otherwise it is really blurry.

![blurryicon](https://user-images.githubusercontent.com/1271053/36991342-6982f22e-2075-11e8-9991-e4bc152b3a37.png)

This seemed a little better:
```css
.site-header .menu-toggle::before {
	margin-right: 5px;
	text-rendering: auto;
	float: left;
	position: relative;
	top: 1px;
}
```

**Comment by seothemes** [comment]
Can I suggest using a CSS-only harmburger icon or an SVG here instead of dashicons?

This solves the problem of blurriness on IE and it doesn’t really make sense to load an entire font for just one icon.

**Comment by dreamwhisper** [comment]
It is also in our WooC CSS and our other menu toggles. I think 5 icons.

**Comment by bgardner** [comment]
> This solves the problem of blurriness on IE and it doesn’t really make sense to load an entire font for just one icon.

I do agree with this statement.

**Comment by dreamwhisper** [comment]
We decided to stick with Dashicons. Set for Needs Testing.

**Comment by nickcernis** [comment]
Confirmed.

![menu-alignment](https://user-images.githubusercontent.com/647669/37624062-22f105c8-2bc7-11e8-8b21-acd250a0126b.png)

**Comment by srikat** [comment]
> Can I suggest using a CSS-only harmburger icon or an SVG here instead of dashicons?
> 
> This solves the problem of blurriness on IE and it doesn’t really make sense to load an entire font for just one icon.

https://sridharkatakam.com/css-sub-menu-toggles-in-genesis/
