### ISSUE TITLE
Beta: .nav-primary should be moved down to clear left float when the hamburger appears

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#84]
Problem:

![screenshot](https://d.pr/i/ID5D26+)

Solution:

```
@media only screen and (max-width: 959px) {
	.nav-primary {
		clear: left;
	}
}
```

![screenshot](https://d.pr/i/pk3Pqm+)

**Comment by nickcernis** [comment]
Confirmed:

![nav-float](https://user-images.githubusercontent.com/647669/37624227-b8d380ac-2bc7-11e8-9fca-0902c74812e6.png)
