### ISSUE TITLE
Beta: No max-width for wrap?

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#85]
I see that there's no `max-width` value and `margin: 0 auto` for `.wrap` anymore.

Older (current stable) Sample has

```
.site-inner,
.wrap {
	margin: 0 auto;
	max-width: 1280px;
}
```

Is this by design?

**Comment by bgardner** [comment]
It is, as we've gone away with the boxed look. Previous version used the .wrap for .site-header, .nav-primary, .footer-widgets, and site-footer. Now, there's really one one instance where that is required:

```
.footer-widgets .wrap {
    max-width: 1140px;
}
```
Moreso relevant if https://github.com/copyblogger/genesis-sample/issues/82 happens.
