### ISSUE TITLE
Beta: Minor CSS enhancement

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#86]
```
.footer-widgets .wrap {
	margin-left: auto;
	margin-right: auto;
}
```

could be shortened as:

```
.footer-widgets .wrap {
	margin: 0 auto;
}
```

**Comment by bgardner** [comment]
I think this is six to one, half dozen to another. I used to go with the former, but doesn't that unnecessarily declare the top/bottom margins in this case? In the spirit of pruning (yes, I realize this results in two lines—ironic) the CSS....

**Comment by bgardner** [comment]
I'm going to leave this as is, and close the ticket.
