### ISSUE TITLE
[Request] Features needed

### ISSUE THREAD

**Issue by aryanrajseo** [copyblogger/genesis-sample#87]
I don't know if this makes any sense. I am working with Genesis sample beta and haven't found any problem just something I missed is here

1. Pricing template. I have not found the pricing feature.
2. Replacing Dashicons with Ionicons <3.  Some minor tweaks needed.
3. Adding search icon next to the menu(inline) moth on mobile and pc. (Tut will be delivered by Srikat)
4. Adding some social media icons next to the menu.
5. The full-width post should have a custom featured image(banner) set on top.
6. A shortcode to list out  5 posts as "Latest Post" on the custom homepage.

Thank you.

**Comment by bgardner** [comment]
Closing this, as I don't think we will be adding any of these into Sample (which is supposed to serve as a base, not a custom theme)

The items on this list might be a good fit for tutorials from someone in the community, however.
