### ISSUE TITLE
header code script gets some additional ///

### ISSUE THREAD

**Issue by sigul** [copyblogger/genesis-sample#92]
Not sure it's related to the beta, but just happened

the header code added in genesis settings gets some additional slash after installing the beta theme: 

from 
`<link rel="stylesheet" href="https://use.typekit.net/kpa1zlv.css">`

to 
`<link rel=\\\\\\\"stylesheet\\\\\\\" href=\\\\\\\"https://use.typekit.net/kpa1zlv.css\\\\\\\">`

and then, if you edit the code in the Genesis settings, the website goes down with bad gateway error.

**Comment by nickcernis** [comment]
Thanks for the report, @sigul. We have a report in the main Genesis repo for this (this is the Genesis Sample theme repo). It's being taken care of there and a fix will be made in Genesis 2.6.1.
